sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /kinect2_tripodA/qhd/points
    max_range: 2.5
    point_subsample: 10
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 0.5
    filtered_cloud_topic: filtered_cloud
